/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base_de_donnee;

/**
 *
 * @author hp
 */
public class Principale extends javax.swing.JFrame {

    /**
     * Creates new form Principale
     */
    public Principale() {
        initComponents();
        setSize(495, 300);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnretour = new javax.swing.JButton();
        btnutilisateur = new javax.swing.JButton();
        btnProduit = new javax.swing.JButton();
        btninfogeneral = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("    Menu Principale");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 30, 140, 30);

        btnretour.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnretour.setForeground(new java.awt.Color(0, 0, 204));
        btnretour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/retour.jpg"))); // NOI18N
        btnretour.setText("Retour");
        btnretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretourActionPerformed(evt);
            }
        });
        getContentPane().add(btnretour);
        btnretour.setBounds(290, 157, 190, 43);

        btnutilisateur.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnutilisateur.setForeground(new java.awt.Color(0, 0, 204));
        btnutilisateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/users.png"))); // NOI18N
        btnutilisateur.setText("Utilisateur");
        btnutilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnutilisateurActionPerformed(evt);
            }
        });
        getContentPane().add(btnutilisateur);
        btnutilisateur.setBounds(20, 97, 220, 43);

        btnProduit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnProduit.setForeground(new java.awt.Color(0, 0, 204));
        btnProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/produitt.jpg"))); // NOI18N
        btnProduit.setText("Produit");
        btnProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduitActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduit);
        btnProduit.setBounds(290, 97, 190, 43);

        btninfogeneral.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btninfogeneral.setForeground(new java.awt.Color(0, 0, 204));
        btninfogeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/info.jpg"))); // NOI18N
        btninfogeneral.setText("Info Générale");
        btninfogeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninfogeneralActionPerformed(evt);
            }
        });
        getContentPane().add(btninfogeneral);
        btninfogeneral.setBounds(20, 157, 217, 43);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 490, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretourActionPerformed
        FenConnection a = new FenConnection();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnretourActionPerformed

    private void btnutilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnutilisateurActionPerformed
       utilisateur u = new utilisateur();
       u.setVisible(true);
    }//GEN-LAST:event_btnutilisateurActionPerformed

    private void btnProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduitActionPerformed
        Produit i = new Produit();
        i.setVisible(true);
    }//GEN-LAST:event_btnProduitActionPerformed

    private void btninfogeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninfogeneralActionPerformed
        Cachier v = new Cachier();
        v.setVisible(true);
    }//GEN-LAST:event_btninfogeneralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProduit;
    private javax.swing.JButton btninfogeneral;
    private javax.swing.JButton btnretour;
    private javax.swing.JButton btnutilisateur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
