/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base_de_donnee;

import Application.BDD;
import Application.Parameter;
import Application.ResultSetTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Produit extends javax.swing.JFrame {

    ResultSet rs;
    BDD db;
    public Produit() {
         db = new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
         table();
        setSize(1131, 461);
        setResizable(false);
        setLocationRelativeTo(null);
    }
    public void table() {
        String t[] = {"id","code_prod","reference","designation","rangement","fournisseur","remise","prix","stock"};
        rs = db.querySelect(t, "produit");
        table_prod.setModel(new ResultSetTableModel(rs));
    }
    void actualiser (){
       txtcode_prod.setText("");
       txtreference.setText("");
       txtdesignation.setText("");
       txtrangement.setText("");
       txtfournisseur.setText("");
       txtremise.setText("");
       txtprix.setText("");
       txtrecherche.setText("");
       txtstock.setText("");
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtprix = new javax.swing.JTextField();
        txtcode_prod = new javax.swing.JTextField();
        txtreference = new javax.swing.JTextField();
        txtdesignation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prod = new javax.swing.JTable();
        btnactualiser = new javax.swing.JButton();
        btnrechercher = new javax.swing.JButton();
        btnmodifier = new javax.swing.JButton();
        btnsupprimer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtrangement = new javax.swing.JTextField();
        txtfournisseur = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtrecherche = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtremise = new javax.swing.JTextField();
        combrech_prod = new javax.swing.JComboBox<>();
        jlabel = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        btnajouter = new javax.swing.JButton();
        btnretour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Code du produit");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 120, 40);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Reference");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 120, 40);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Designation");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 120, 40);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Rangement");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 190, 120, 40);
        getContentPane().add(txtprix);
        txtprix.setBounds(140, 350, 140, 40);
        getContentPane().add(txtcode_prod);
        txtcode_prod.setBounds(140, 10, 140, 40);
        getContentPane().add(txtreference);
        txtreference.setBounds(140, 70, 140, 40);
        getContentPane().add(txtdesignation);
        txtdesignation.setBounds(140, 130, 140, 40);

        table_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Code_du_produit", "Reference", "Designation", "Rangement", "Fournisseur", "Remise_en_%", "Prix", "stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_prod);
        if (table_prod.getColumnModel().getColumnCount() > 0) {
            table_prod.getColumnModel().getColumn(0).setResizable(false);
            table_prod.getColumnModel().getColumn(1).setResizable(false);
            table_prod.getColumnModel().getColumn(2).setResizable(false);
            table_prod.getColumnModel().getColumn(3).setResizable(false);
            table_prod.getColumnModel().getColumn(4).setResizable(false);
            table_prod.getColumnModel().getColumn(5).setResizable(false);
            table_prod.getColumnModel().getColumn(7).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 0, 830, 140);

        btnactualiser.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnactualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/actualiser.jpg"))); // NOI18N
        btnactualiser.setText("ACTUALISER");
        btnactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualiserActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualiser);
        btnactualiser.setBounds(590, 190, 170, 40);

        btnrechercher.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnrechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/rechercher.jpg"))); // NOI18N
        btnrechercher.setText("Rechercher");
        btnrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechercherActionPerformed(evt);
            }
        });
        getContentPane().add(btnrechercher);
        btnrechercher.setBounds(330, 290, 160, 40);

        btnmodifier.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/modifier.jpg"))); // NOI18N
        btnmodifier.setText("MODIFIER");
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodifier);
        btnmodifier.setBounds(440, 190, 145, 40);

        btnsupprimer.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnsupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/supprimer.jpg"))); // NOI18N
        btnsupprimer.setText("SUPPRIMER");
        btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(btnsupprimer);
        btnsupprimer.setBounds(770, 190, 157, 40);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Prix");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 350, 120, 40);

        txtrangement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrangementActionPerformed(evt);
            }
        });
        getContentPane().add(txtrangement);
        txtrangement.setBounds(140, 190, 140, 40);
        getContentPane().add(txtfournisseur);
        txtfournisseur.setBounds(140, 250, 140, 40);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Recherche du produit par categorie");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 240, 260, 40);

        txtrecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrechercheActionPerformed(evt);
            }
        });
        getContentPane().add(txtrecherche);
        txtrecherche.setBounds(500, 290, 140, 40);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Fournisseur");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 250, 120, 40);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Remise en %");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 300, 120, 40);
        getContentPane().add(txtremise);
        txtremise.setBounds(140, 300, 140, 40);

        combrech_prod.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        combrech_prod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "Code_prod", "reference", "designation", "rangement", "fournisseur", "remise", "prix", "stock", " " }));
        getContentPane().add(combrech_prod);
        combrech_prod.setBounds(660, 250, 180, 40);

        jlabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlabel.setForeground(new java.awt.Color(51, 51, 255));
        jlabel.setText("Stock");
        getContentPane().add(jlabel);
        jlabel.setBounds(10, 400, 120, 40);
        getContentPane().add(txtstock);
        txtstock.setBounds(140, 400, 140, 40);

        btnajouter.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/enregistrer.jpg"))); // NOI18N
        btnajouter.setText("AJOUTER");
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });
        getContentPane().add(btnajouter);
        btnajouter.setBounds(290, 190, 140, 40);

        btnretour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnretour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/retour.jpg"))); // NOI18N
        btnretour.setText("Retour");
        btnretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretourActionPerformed(evt);
            }
        });
        getContentPane().add(btnretour);
        btnretour.setBounds(950, 190, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/produit.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1130, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechercherActionPerformed
        if (txtrecherche .getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP veuillez saisir la donnee");
        } else {
            if (combrech_prod.getSelectedItem().equals("id")) {
                rs = db.querySelectAll("produit", "id LIKE '%" + txtrecherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (combrech_prod.getSelectedItem().equals("code_prod")) {
                rs = db.querySelectAll("produit", "code_prod LIKE '%" + txtrecherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (combrech_prod.getSelectedItem().equals("reference")) {
                rs = db.querySelectAll("produit", "reference LIKE '%" + txtrecherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (combrech_prod.getSelectedItem().equals("designation")) {
                rs = db.querySelectAll("produit", "designation LIKE '%" + txtrecherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (combrech_prod.getSelectedItem().equals("rangement")) {
                rs = db.querySelectAll("produit", "rangement LIKE '%" + txtrecherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if (combrech_prod.getSelectedItem().equals("fournisseur")) {
                rs = db.querySelectAll("produit", "fournisseur LIKE '%" + txtrecherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if (combrech_prod.getSelectedItem().equals("remise")) {
                rs = db.querySelectAll("produit", "remise LIKE '%" + txtrecherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if (combrech_prod.getSelectedItem().equals("prix")) {
                rs = db.querySelectAll("produit", "prix LIKE '%" + txtrecherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if (combrech_prod.getSelectedItem().equals("stock")) {
                rs = db.querySelectAll("produit", "stock LIKE '%" + txtrecherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
        } 
    }//GEN-LAST:event_btnrechercherActionPerformed

    private void txtrechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrechercheActionPerformed

    private void txtrangementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrangementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrangementActionPerformed

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        if ( txtcode_prod.getText().equals("") || txtreference.getText().equals("")
                || txtdesignation.getText().equals("")|| txtrangement.getText().equals("") || txtfournisseur.getText().equals("") ||
                txtremise.getText().equals("") || txtprix.getText().equals("")|| txtstock.getText().equals("") ) {
            JOptionPane.showMessageDialog(this, "veillez saisir les informations à modifier");
        }else {
            String [] colon = {"code_prod","reference","designation","rangement","fournisseur","remise","prix","stock"};
            String [] inf = {txtcode_prod.getText(),txtreference.getText(), txtdesignation.getText() ,txtrangement.getText() ,txtfournisseur.getText(),
                txtremise.getText(),txtprix.getText(),txtstock.getText()};
            String id = String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(),0));
            System.out.println(db.queryUpdate("produit", colon,inf,"id='"+ id +"'"));
            table();
            actualiser();
        }
    }//GEN-LAST:event_btnmodifierActionPerformed

    private void btnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprimerActionPerformed
         String id = String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "etes vous sur de vouloir supprimer ","Attention!!!",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("produit","id="+ id);
        }else {
            return ;
        }
        table();
    }//GEN-LAST:event_btnsupprimerActionPerformed

    private void btnactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualiserActionPerformed
        actualiser();table();
    }//GEN-LAST:event_btnactualiserActionPerformed

    private void table_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prodMouseClicked
         this.txtcode_prod.setText(String.valueOf(this.table_prod.getValueAt(this.table_prod.getSelectedRow(),1)));
        this.txtrangement.setText(String.valueOf(this.table_prod.getValueAt(this.table_prod.getSelectedRow(),2)));
        this.txtreference.setText(String.valueOf(this.table_prod.getValueAt(this.table_prod.getSelectedRow(),3)));
        this.txtdesignation.setText(String.valueOf(this.table_prod.getValueAt(this.table_prod.getSelectedRow(),4)));
         this.txtremise.setText(String.valueOf(this.table_prod.getValueAt(this.table_prod.getSelectedRow(),5)));
          this.txtstock.setText(String.valueOf(this.table_prod.getValueAt(this.table_prod.getSelectedRow(),6)));
           this.txtfournisseur.setText(String.valueOf(this.table_prod.getValueAt(this.table_prod.getSelectedRow(),7)));
            this.txtprix.setText(String.valueOf(this.table_prod.getValueAt(this.table_prod.getSelectedRow(),8)));
    }//GEN-LAST:event_table_prodMouseClicked

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
         if ( txtcode_prod.getText().equals("") || txtreference.getText().equals("")
                || txtdesignation.getText().equals("")|| txtrangement.getText().equals("") || txtfournisseur.getText().equals("") ||
                txtremise.getText().equals("") || txtprix.getText().equals("")|| txtstock.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "veillez saisir toutes les informations ");
        }else {
            String [] colon = {"code_prod","reference","designation","rangement","fournisseur","remise","prix","stock"};
            String [] inf = {txtcode_prod.getText(),txtreference.getText(), txtdesignation.getText() ,txtrangement.getText() ,txtfournisseur.getText(),
                txtremise.getText(),txtprix.getText(),txtstock.getText()};
            System.out.println(db.queryInsert("produit", colon,inf));
            table();
            actualiser();
        }
    }//GEN-LAST:event_btnajouterActionPerformed

    private void btnretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretourActionPerformed
        Principale a = new Principale();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnretourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualiser;
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnrechercher;
    private javax.swing.JButton btnretour;
    private javax.swing.JButton btnsupprimer;
    private javax.swing.JComboBox<String> combrech_prod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTable table_prod;
    private javax.swing.JTextField txtcode_prod;
    private javax.swing.JTextField txtdesignation;
    private javax.swing.JTextField txtfournisseur;
    private javax.swing.JTextField txtprix;
    private javax.swing.JTextField txtrangement;
    private javax.swing.JTextField txtrecherche;
    private javax.swing.JTextField txtreference;
    private javax.swing.JTextField txtremise;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
